# Generated by Django 5.0.6 on 2024-07-02 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='TodoItem',
        ),
        migrations.AlterModelOptions(
            name='todoitem',
            options={},
        ),
    ]
